#!/bin/bash

########################################################
# For Windows: copy this file to .git\hooks\pre-commit #
########################################################

PYTHON_INTERPRETER="C:\\ProgramData\\miniconda3\\envs\\icpp-pro\\python.exe"

# Change to the root directory of the repository
cd "$(git rev-parse --show-toplevel)"
echo "Running from directory: "
pwd

# Define the path to the all-test bash script
PRE_COMMIT_SCRIPT_PATH="./windows-all-tests.sh"

# Function to check the exit status of the last executed command
check_exit_status() {
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

# Run the win-all-static.sh script with the Python interpreter and directories as arguments
$PRE_COMMIT_SCRIPT_PATH "$PYTHON_INTERPRETER" "all-static"
check_exit_status

