[build-wasm]
canister = "greet"
did_path = "src/greet.did"
cpp_paths = ["src/*.cpp"]
cpp_include_dirs = ["src/vendors/*"]
cpp_header_paths = ["src/*.h"]
cpp_compile_flags = ["-D JSON_HAS_FILESYSTEM=0"]
cpp_link_flags = []
c_paths = []
c_include_dirs = []
c_header_paths = []
c_compile_flags = []
[build-native]
cpp_paths = ["native/main.cpp"]
cpp_include_dirs = []
cpp_header_paths = ["native/main.h"]
cpp_compile_flags = []
cpp_link_flags = []
c_paths = []
c_include_dirs = []
c_header_paths = []
c_compile_flags = []
